### ISSUE TITLE
I just can't get multi turn tool use to work

### ISSUE THREAD

**Issue by SamSaffron** [anthropics/courses#5]
In multi turn mode API keeps hallucinating a tool use as a standard reply

![image](https://github.com/anthropics/courses/assets/5213/03cd432a-0850-4cb9-be15-06c227928d63)

It is unclear how to encode tool use and result... I am doing this now... 

![image](https://github.com/anthropics/courses/assets/5213/ad182060-d082-4709-9312-4771b89eee16)

A simple payload or API example that illustrates this (just a messages block with a bunch of history in text form) would be enormously helpful.

**Comment by k3baah** [comment]
Just trying to understand the issue here. 

Is it returning a tool block when it's not supposed to? If so,

1. Is the `tool_choice` parameter populated in the api request? eg `{"type": "tool", "name": "web_browser"}`
2. Have you tried tweaking your prompt to give it more context on when it should/shouldn't use tools?

**Comment by SamSaffron** [comment]
I think this can be closed, I sorted this per the encoding rules here: 

https://github.com/discourse/discourse-ai/blob/main/lib/completions/dialects/claude_tools.rb

That said, the documentation did not make it easy. id, name, input, type need to be "just right" and there are no sample payloads on the docs side to make live easy for implementers.

**Comment by tungd776** [comment]
```

```
